tasks:
  - init: "gp open ./src/app.js && clear && echo Installing Tabris, please stand by... && npm install git://github.com:eclipsesource/tabris-js-cli.git -g"
    command: "clear && npm install && npm run gitpod"
ports:
  - port: 8080
    onOpen: open-preview
